[package]
name = "rust-env-by-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
